version: '3.1'

services:
  thunderdome:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    links:
      - db
      - redis
    networks:
      - asgard
    environment:
      APP_DOMAIN: ".127.0.0.1"
      COOKIE_SECURE: "false"
      SMTP_SECURE: "false"
      SMTP_HOST: mail
      SMTP_PORT: 1025
      DB_NAME: thunderdome
      DB_USER: thor
      DB_PASS: odinson
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_POOL_SIZE: 20
      REDIS_MIN_IDLE_CONNS: 10
      REDIS_MAX_RETRIES: 3
      # AI功能配置 - 使用Hugging Face免费API
      CONFIG_AI_ENABLED: "true"
      THUNDERDOME_AI_API_URL: "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.2"
      THUNDERDOME_AI_API_KEY: "replace-your-key" # 请替换为您的Hugging Face令牌
      THUNDERDOME_AI_MODEL: "mistral"
    volumes:
      - ./etc:/etc/thunderdome
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: thunderdome
      POSTGRES_USER: thor
      POSTGRES_PASSWORD: odinson
    ports:
      - 5432:5432
    volumes:
      - thunderdome_data:/var/lib/postgresql/data
    networks:
      - asgard
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thor -d thunderdome"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - asgard
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  mail:
    image: maildev/maildev:2.1.0
    restart: always
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - asgard

networks:
  asgard:

volumes:
  thunderdome_data:
  redis_data:
