version: '3.1'

services:
  thunderdome:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    networks:
      - asgard
    environment:
      APP_DOMAIN: ".127.0.0.1"
      COOKIE_SECURE: "false"
      SMTP_SECURE: "false"
      SMTP_HOST: mail
      SMTP_PORT: 1025
      DB_NAME: thunderdome
      DB_USER: thor
      DB_PASS: odinson
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./etc:/etc/thunderdome
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: thunderdome
      POSTGRES_USER: thor
      POSTGRES_PASSWORD: odinson
    ports:
      - 5432:5432
    volumes:
      - thunderdome_data:/var/lib/postgresql/data
    networks:
      - asgard
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - asgard
  mail:
    image: maildev/maildev:2.1.0
    restart: always
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - asgard

networks:
  asgard:

volumes:
  thunderdome_data:
  redis_data:
